/* Automatically generated by icon2glyph.py */

#pragma once

#include "app_config.h"
#include "nbgl_types.h"

extern uint8_t const C_app_boilerplate_16px_bitmap[29];
extern const nbgl_icon_details_t C_app_boilerplate_16px;

extern uint8_t const C_app_boilerplate_64px_bitmap[187];
extern const nbgl_icon_details_t C_app_boilerplate_64px;

extern uint8_t const C_pin_24_bitmap[49];
extern const nbgl_icon_details_t C_pin_24;

extern uint8_t const C_quarter_circle_bottom_left_32px_1bpp_bitmap[128];
extern const nbgl_icon_details_t C_quarter_circle_bottom_left_32px_1bpp;

extern uint8_t const C_quarter_circle_bottom_left_40px_1bpp_bitmap[200];
extern const nbgl_icon_details_t C_quarter_circle_bottom_left_40px_1bpp;

extern uint8_t const C_quarter_circle_bottom_left_44px_1bpp_bitmap[242];
extern const nbgl_icon_details_t C_quarter_circle_bottom_left_44px_1bpp;

extern uint8_t const C_quarter_circle_top_left_32px_1bpp_bitmap[128];
extern const nbgl_icon_details_t C_quarter_circle_top_left_32px_1bpp;

extern uint8_t const C_quarter_circle_top_left_40px_1bpp_bitmap[200];
extern const nbgl_icon_details_t C_quarter_circle_top_left_40px_1bpp;

extern uint8_t const C_quarter_circle_top_left_44px_1bpp_bitmap[242];
extern const nbgl_icon_details_t C_quarter_circle_top_left_44px_1bpp;

extern uint8_t const C_quarter_disc_bottom_left_32px_1bpp_bitmap[128];
extern const nbgl_icon_details_t C_quarter_disc_bottom_left_32px_1bpp;

extern uint8_t const C_quarter_disc_bottom_left_40px_1bpp_bitmap[200];
extern const nbgl_icon_details_t C_quarter_disc_bottom_left_40px_1bpp;

extern uint8_t const C_quarter_disc_bottom_left_44px_1bpp_bitmap[242];
extern const nbgl_icon_details_t C_quarter_disc_bottom_left_44px_1bpp;

extern uint8_t const C_quarter_disc_top_left_32px_1bpp_bitmap[128];
extern const nbgl_icon_details_t C_quarter_disc_top_left_32px_1bpp;

extern uint8_t const C_quarter_disc_top_left_40px_1bpp_bitmap[200];
extern const nbgl_icon_details_t C_quarter_disc_top_left_40px_1bpp;

extern uint8_t const C_quarter_disc_top_left_44px_1bpp_bitmap[242];
extern const nbgl_icon_details_t C_quarter_disc_top_left_44px_1bpp;

extern uint8_t const C_round_24px_bitmap[47];
extern const nbgl_icon_details_t C_round_24px;

extern uint8_t const C_switch_60_40_bitmap[300];
extern const nbgl_icon_details_t C_switch_60_40;

extern uint8_t const C_Check_Circle_64px_bitmap[571];
extern const nbgl_icon_details_t C_Check_Circle_64px;

extern uint8_t const C_Denied_Circle_64px_bitmap[568];
extern const nbgl_icon_details_t C_Denied_Circle_64px;

extern uint8_t const C_Important_Circle_64px_bitmap[514];
extern const nbgl_icon_details_t C_Important_Circle_64px;

extern uint8_t const C_Review_64px_bitmap[219];
extern const nbgl_icon_details_t C_Review_64px;

extern uint8_t const C_SecurityShield_64px_bitmap[610];
extern const nbgl_icon_details_t C_SecurityShield_64px;

extern uint8_t const C_Warning_64px_bitmap[359];
extern const nbgl_icon_details_t C_Warning_64px;

extern uint8_t const C_left_half_64px_bitmap[192];
extern const nbgl_icon_details_t C_left_half_64px;

extern uint8_t const C_Back_40px_bitmap[148];
extern const nbgl_icon_details_t C_Back_40px;

extern uint8_t const C_Check_40px_bitmap[92];
extern const nbgl_icon_details_t C_Check_40px;

extern uint8_t const C_Check_Circle_40px_bitmap[339];
extern const nbgl_icon_details_t C_Check_Circle_40px;

extern uint8_t const C_Chevron_40px_bitmap[100];
extern const nbgl_icon_details_t C_Chevron_40px;

extern uint8_t const C_Chevron_Back_40px_bitmap[126];
extern const nbgl_icon_details_t C_Chevron_Back_40px;

extern uint8_t const C_Chevron_Next_40px_bitmap[121];
extern const nbgl_icon_details_t C_Chevron_Next_40px;

extern uint8_t const C_Close_40px_bitmap[141];
extern const nbgl_icon_details_t C_Close_40px;

extern uint8_t const C_Denied_Circle_40px_bitmap[326];
extern const nbgl_icon_details_t C_Denied_Circle_40px;

extern uint8_t const C_Erase_40px_bitmap[120];
extern const nbgl_icon_details_t C_Erase_40px;

extern uint8_t const C_Info_40px_bitmap[57];
extern const nbgl_icon_details_t C_Info_40px;

extern uint8_t const C_Maj_40px_bitmap[89];
extern const nbgl_icon_details_t C_Maj_40px;

extern uint8_t const C_Maj_Lock_40px_bitmap[85];
extern const nbgl_icon_details_t C_Maj_Lock_40px;

extern uint8_t const C_Mini_Push_40px_bitmap[214];
extern const nbgl_icon_details_t C_Mini_Push_40px;

extern uint8_t const C_Next_40px_bitmap[142];
extern const nbgl_icon_details_t C_Next_40px;

extern uint8_t const C_Plus_40px_bitmap[62];
extern const nbgl_icon_details_t C_Plus_40px;

extern uint8_t const C_QRCode_40px_bitmap[161];
extern const nbgl_icon_details_t C_QRCode_40px;

extern uint8_t const C_Settings_40px_bitmap[411];
extern const nbgl_icon_details_t C_Settings_40px;

extern uint8_t const C_Space_40px_bitmap[44];
extern const nbgl_icon_details_t C_Space_40px;

extern uint8_t const C_Warning_40px_bitmap[239];
extern const nbgl_icon_details_t C_Warning_40px;

extern uint8_t const C_radio_active_40px_bitmap[295];
extern const nbgl_icon_details_t C_radio_active_40px;

extern uint8_t const C_radio_inactive_40px_bitmap[205];
extern const nbgl_icon_details_t C_radio_inactive_40px;

extern uint8_t const C_app_boilerplate_40px_bitmap[236];
extern const nbgl_icon_details_t C_app_boilerplate_40px;

