#define HAVE_LOCAL_APDU_BUFFER
#define IO_HID_EP_LENGTH 64
#define USB_SEGMENT_SIZE 64
#define OS_IO_SEPROXYHAL
#define HAVE_IO_USB
#define HAVE_L4_USBLIB
#define HAVE_USB_APDU
#define __IO volatile
#define IO_USB_MAX_ENDPOINTS 6
#define IO_SEPROXYHAL_BUFFER_SIZE_B 300
#define main _start

#define NBGL_QRCODE

// from Makefile.defines
#define HAVE_BAGL_FONT_INTER_REGULAR_24PX
#define HAVE_BAGL_FONT_INTER_SEMIBOLD_24PX
#define HAVE_BAGL_FONT_INTER_MEDIUM_32PX
#define HAVE_INAPP_BLE_PAIRING
#define HAVE_NBGL
#define HAVE_PIEZO_SOUND
#define HAVE_SE_TOUCH
#define HAVE_SE_EINK_DISPLAY
#define NBGL_PAGE
#define NBGL_USE_CASE
#define SCREEN_SIZE_WALLET

#define HAVE_BLE
#define HAVE_BLE_APDU
#define BLE_COMMAND_TIMEOUT_MS 2000
#define BLE_SEGMENT_SIZE 32