/* Automatically generated by icon2glyph.py */

#pragma once

#include "app_config.h"
#include "nbgl_types.h"

extern uint8_t const C_app_boilerplate_16px_bitmap[29];
extern const nbgl_icon_details_t C_app_boilerplate_16px;

extern uint8_t const C_app_boilerplate_64px_bitmap[187];
extern const nbgl_icon_details_t C_app_boilerplate_64px;

extern uint8_t const C_pin_24_bitmap[49];
extern const nbgl_icon_details_t C_pin_24;

extern uint8_t const C_quarter_circle_bottom_left_32px_1bpp_bitmap[128];
extern const nbgl_icon_details_t C_quarter_circle_bottom_left_32px_1bpp;

extern uint8_t const C_quarter_circle_bottom_left_40px_1bpp_bitmap[200];
extern const nbgl_icon_details_t C_quarter_circle_bottom_left_40px_1bpp;

extern uint8_t const C_quarter_circle_bottom_left_44px_1bpp_bitmap[242];
extern const nbgl_icon_details_t C_quarter_circle_bottom_left_44px_1bpp;

extern uint8_t const C_quarter_circle_top_left_32px_1bpp_bitmap[128];
extern const nbgl_icon_details_t C_quarter_circle_top_left_32px_1bpp;

extern uint8_t const C_quarter_circle_top_left_40px_1bpp_bitmap[200];
extern const nbgl_icon_details_t C_quarter_circle_top_left_40px_1bpp;

extern uint8_t const C_quarter_circle_top_left_44px_1bpp_bitmap[242];
extern const nbgl_icon_details_t C_quarter_circle_top_left_44px_1bpp;

extern uint8_t const C_quarter_disc_bottom_left_32px_1bpp_bitmap[128];
extern const nbgl_icon_details_t C_quarter_disc_bottom_left_32px_1bpp;

extern uint8_t const C_quarter_disc_bottom_left_40px_1bpp_bitmap[200];
extern const nbgl_icon_details_t C_quarter_disc_bottom_left_40px_1bpp;

extern uint8_t const C_quarter_disc_bottom_left_44px_1bpp_bitmap[242];
extern const nbgl_icon_details_t C_quarter_disc_bottom_left_44px_1bpp;

extern uint8_t const C_quarter_disc_top_left_32px_1bpp_bitmap[128];
extern const nbgl_icon_details_t C_quarter_disc_top_left_32px_1bpp;

extern uint8_t const C_quarter_disc_top_left_40px_1bpp_bitmap[200];
extern const nbgl_icon_details_t C_quarter_disc_top_left_40px_1bpp;

extern uint8_t const C_quarter_disc_top_left_44px_1bpp_bitmap[242];
extern const nbgl_icon_details_t C_quarter_disc_top_left_44px_1bpp;

extern uint8_t const C_round_24px_bitmap[47];
extern const nbgl_icon_details_t C_round_24px;

extern uint8_t const C_switch_60_40_bitmap[300];
extern const nbgl_icon_details_t C_switch_60_40;

extern uint8_t const C_Check_Circle_64px_bitmap[571];
extern const nbgl_icon_details_t C_Check_Circle_64px;

extern uint8_t const C_Denied_Circle_64px_bitmap[568];
extern const nbgl_icon_details_t C_Denied_Circle_64px;

extern uint8_t const C_Important_Circle_64px_bitmap[514];
extern const nbgl_icon_details_t C_Important_Circle_64px;

extern uint8_t const C_Review_64px_bitmap[219];
extern const nbgl_icon_details_t C_Review_64px;

extern uint8_t const C_SecurityShield_64px_bitmap[610];
extern const nbgl_icon_details_t C_SecurityShield_64px;

extern uint8_t const C_Warning_64px_bitmap[359];
extern const nbgl_icon_details_t C_Warning_64px;

extern uint8_t const C_left_half_64px_bitmap[192];
extern const nbgl_icon_details_t C_left_half_64px;

extern uint8_t const C_Back_32px_bitmap[141];
extern const nbgl_icon_details_t C_Back_32px;

extern uint8_t const C_Check_32px_bitmap[74];
extern const nbgl_icon_details_t C_Check_32px;

extern uint8_t const C_Check_Circle_32px_bitmap[286];
extern const nbgl_icon_details_t C_Check_Circle_32px;

extern uint8_t const C_Chevron_32px_bitmap[88];
extern const nbgl_icon_details_t C_Chevron_32px;

extern uint8_t const C_Chevron_Back_32px_bitmap[113];
extern const nbgl_icon_details_t C_Chevron_Back_32px;

extern uint8_t const C_Chevron_Next_32px_bitmap[113];
extern const nbgl_icon_details_t C_Chevron_Next_32px;

extern uint8_t const C_Close_32px_bitmap[112];
extern const nbgl_icon_details_t C_Close_32px;

extern uint8_t const C_Denied_Circle_32px_bitmap[280];
extern const nbgl_icon_details_t C_Denied_Circle_32px;

extern uint8_t const C_Erase_32px_bitmap[80];
extern const nbgl_icon_details_t C_Erase_32px;

extern uint8_t const C_Important_Circle_32px_bitmap[257];
extern const nbgl_icon_details_t C_Important_Circle_32px;

extern uint8_t const C_Info_32px_bitmap[53];
extern const nbgl_icon_details_t C_Info_32px;

extern uint8_t const C_Maj_32px_bitmap[75];
extern const nbgl_icon_details_t C_Maj_32px;

extern uint8_t const C_Maj_Lock_32px_bitmap[71];
extern const nbgl_icon_details_t C_Maj_Lock_32px;

extern uint8_t const C_Mini_Push_32px_bitmap[188];
extern const nbgl_icon_details_t C_Mini_Push_32px;

extern uint8_t const C_Next_32px_bitmap[137];
extern const nbgl_icon_details_t C_Next_32px;

extern uint8_t const C_QRCode_32px_bitmap[143];
extern const nbgl_icon_details_t C_QRCode_32px;

extern uint8_t const C_Settings_32px_bitmap[281];
extern const nbgl_icon_details_t C_Settings_32px;

extern uint8_t const C_Space_32px_bitmap[41];
extern const nbgl_icon_details_t C_Space_32px;

extern uint8_t const C_Warning_32px_bitmap[201];
extern const nbgl_icon_details_t C_Warning_32px;

extern uint8_t const C_radio_active_32px_bitmap[288];
extern const nbgl_icon_details_t C_radio_active_32px;

extern uint8_t const C_radio_inactive_32px_bitmap[201];
extern const nbgl_icon_details_t C_radio_inactive_32px;

extern uint8_t const C_app_boilerplate_32px_bitmap[77];
extern const nbgl_icon_details_t C_app_boilerplate_32px;

