[target.nanos]
runner = "speculos -m nanos --display=headless"

[target.nanox]
runner = "speculos -m nanox -k 2.0.2 --display=headless"

[target.nanosplus]
runner = "speculos -m nanosp -k 1.0.3 --display=headless"

[unstable]
build-std = ["core"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "nanosplus.json"